"use client"
import 'aos/dist/aos.css';
import './globals.css'
import "../styles/fonts.css";
import "bootstrap/dist/css/bootstrap.min.css";

import AOS from 'aos';
import { useEffect } from 'react';

export const metadata = {
  title: 'RjR',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  useEffect (() => {
    // here you can add your aos options
    AOS.init({
      offset: 100,
    });
  }, []);
  return (
    <html lang="en">
      <head>
      </head>
      <body >{children}</body>
    </html>
  )
}
