import 'aos/dist/aos.css';
import './globals.css'
import "../styles/fonts.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: 'RjR',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body >{children}</body>
    </html>
  )
}
